# =============================================================================
# General
# =============================================================================
unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g base-index 1              # Window numbers start at 1
setw -g mode-keys vi             # Vi bindings in copy mode
set -s escape-time 0             # No delay after Esc
set -g detach-on-destroy off     # Stay in tmux when session closes
set -g renumber-windows on       # No gaps after closing windows
set -g mouse on

set -g default-terminal "tmux-256color"
if-shell "uname | grep -q MINGW" "set -g default-shell 'C:/Program Files/Git/bin/bash.exe'"
set-option -sa terminal-overrides ',xterm-256color:RGB'
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# =============================================================================
# Panes
# =============================================================================
bind - split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"

bind c new-window -c "#{pane_current_path}"

unbind '"'
unbind %

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set-option -g pane-active-border-style "fg=colour182,bg=default"
set-option -g pane-border-style "fg=colour189,bg=default"

# =============================================================================
# Windows
# =============================================================================
bind m choose-window
bind X next-layout
bind Z previous-layout

# =============================================================================
# Sessions
# =============================================================================
bind f run-shell "tmux neww tmux-sessionizer"
bind N command-prompt -p "Session name:" "new-session -s '%%'"

set-hook -g after-new-session 'resize-pane -D 1'

# =============================================================================
# Status bar
# =============================================================================
set -g status off
set -g status-style fg=black,bg=colour175
set -g status-left "[#S] "
set -g status-right "💞 %Y-%m-%d %H:%M"

# =============================================================================
# Utilities
# =============================================================================
bind r source-file ~/.tmux.conf \; display-message "🗣️ Config reloaded!"
bind ? display-popup -E -w 80% -h 60% "tmux list-keys | bat -l bash --color=always --style=plain | fzf --ansi"
bind t display-popup -E -w 30% -h 40% "tmux-launcher"
