# Infrastructure tools — Portainer, Paisa, and Dozzle.
#
# Installs a launcher (.local/bin/infra, `infra up|down|status|pull`) that drives
# a local docker-compose stack.
#
# Gated to Linux hosts with `role == "server"` in flake.nix.
{ pkgs, lib, role ? "client", ... }:
let
  serverHost = pkgs.stdenv.isLinux && role == "server";
  infraCompose = pkgs.writeText "infra-compose.yml" ''
    # Generated by home/infra.nix — do not edit.
    services:
      portainer:
        image: portainer/portainer-ce:latest
        restart: unless-stopped
        ports:
          - "127.0.0.1:9000:9000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data
        command: "--no-setup-token"
      
      paisa:
        image: ananthakumaran/paisa:latest-hledger
        restart: unless-stopped
        ports:
          - "127.0.0.1:7501:7500"
        volumes:
          - ''${HOME}/finance:/root/Documents/paisa
      
      dozzy:
        image: amir20/dozzle:latest
        restart: unless-stopped
        ports:
          - "127.0.0.1:8081:8080"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

      netdata:
        image: netdata/netdata:latest
        restart: unless-stopped
        ports:
          - "127.0.0.1:19999:19999"
        cap_add:
          - SYS_PTRACE
          - SYS_ADMIN
        security_opt:
          - apparmor:unconfined
        volumes:
          - netdataconfig:/etc/netdata
          - netdatalib:/var/lib/netdata
          - netdatacache:/var/cache/netdata
          - /etc/passwd:/host/etc/passwd:ro
          - /etc/group:/host/etc/group:ro
          - /etc/os-release:/host/etc/os-release:ro
          - /proc:/host/proc:ro
          - /sys:/host/sys:ro
          - /var/run/docker.sock:/var/run/docker.sock:ro
    
    volumes:
      portainer_data:
        external: true
      netdataconfig:
      netdatalib:
      netdatacache:
  '';
in
{
  home.file = lib.mkIf serverHost {
    ".local/bin/infra" = {
      source = ../.local/bin/infra;
      executable = true;
    };
    ".config/infra/docker-compose.yml".source = infraCompose;
  };
}
