# Infrastructure tools — Portainer, Paisa, and Dozzle.
#
# Installs a launcher (.local/bin/infra, `infra up|down|status|pull`) that drives
# a local docker-compose stack.
#
# Gated to Linux hosts with `role == "server"` in flake.nix.
{ pkgs, lib, role ? "client", ... }:
let
  serverHost = pkgs.stdenv.isLinux && role == "server";
  infraCompose = pkgs.writeText "infra-compose.yml" ''
    # Generated by home/infra.nix — do not edit.
    services:
      portainer:
        image: portainer/portainer-ce:latest
        restart: unless-stopped
        ports:
          - "127.0.0.1:9000:9000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data
        command: "--no-setup-token"
      
      paisa:
        image: ananthakumaran/paisa:latest-hledger
        restart: unless-stopped
        ports:
          - "127.0.0.1:7500:7500"
        volumes:
          - ''${HOME}/finance:/root/Documents/paisa
      
      dozzy:
        image: amir20/dozzle:latest
        restart: unless-stopped
        ports:
          - "127.0.0.1:8081:8080"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
    
    volumes:
      portainer_data:
        external: true
  '';
in
{
  home.file = lib.mkIf serverHost {
    ".local/bin/infra" = {
      source = ../.local/bin/infra;
      executable = true;
    };
    ".config/infra/docker-compose.yml".source = infraCompose;
  };
}
