# system-proxy — the box's single system-wide nginx reverse proxy (tier1).
#
# Everything else on this host binds only to loopback (meddy's own nginx,
# tsvc-managed services like Portainer and Paisa); this is the ONLY thing bound
# to the real 0.0.0.0:80/443. It terminates TLS with one mkcert cert covering
# every domain below and fans out by Host header to each project's loopback
# port — each project keeps owning its own internal routing, so compose
# projects never need to share a docker network with each other or with this
# proxy. Runs with --network host (see the launcher) so its own 127.0.0.1 is
# the real host loopback — those loopback-published ports are NOT reachable via
# the docker0 bridge gateway (host.docker.internal), only genuine loopback.
# See .local/bin/system-proxy for the launcher itself.
#
# Installs the `system-proxy` launcher (.local/bin/system-proxy) plus its
# rendered nginx config. The TLS cert itself is NOT nix-managed (mkcert writes
# host-local state) — after `hm-switch`, run `system-proxy certs` once, then
# `system-proxy start`. Docker's `--restart=unless-stopped` means it survives
# reboots on its own from then on, same as tsvc/portainer (see home/tsvc.nix).
#
# Gated to Linux `server` hosts, same as tsvc/portainer.
#
# TWO NAMESPACES, one proxy (both fixed per-host below):
#
#   rootDomain     — the project/SaaS namespace. Fans out to a project's own
#                    tier2 nginx, which owns its internal subdomain split.
#                    meddy is the only project deployed here today; extend
#                    defaultConf as more join.
#   internalDomain — this host's own infrastructure tools (Portainer, Paisa).
#                    Each is a tsvc service that already has a tailnet URL
#                    (https://<svc>.<tailnet>.ts.net); these names are the
#                    short, host-local alias for the same thing, served off
#                    this box's own cert. See home/tsvc/services/*.env.
#
# Why ".internal" for the infra namespace: ICANN reserved it for private use,
# so it can never be delegated publicly — a name here is guaranteed never to
# collide with something real, which is exactly the property a fake local
# domain needs. (".test" is RFC 6761-reserved with the same guarantee; the
# project namespace deliberately gives that up — see below.)
#
# Why a real public name (dev.meddy.com) for the project namespace: it matches
# the FQDN the app is actually served under in prod, so cookie scope, CORS
# origins and redirect URIs behave the same in dev as they will in production
# — the parity that a .test name can't give you. The tradeoff is that this is
# split-horizon DNS over a name that genuinely exists in public DNS: the
# dnsmasq rule in darwin/default.nix hijacks dev.meddy.com and everything under
# it for any host running this config, so if a real dev.meddy.com is ever
# deployed, those hosts will not be able to reach it. meddy.com itself and its
# other subdomains are untouched — the override is scoped to the dev. label.
{ lib, pkgs, role ? "client", ... }:
let
  enable = pkgs.stdenv.isLinux && role == "server";
  rootDomain = "dev.meddy.com";
  internalDomain = "alien.internal";

  defaultConf = pkgs.writeText "system-proxy-default.conf" ''
    # Generated by home/system-proxy.nix — do not edit, edit the .nix source.
    server {
        listen 80;
        listen [::]:80;
        server_name ${rootDomain} *.${rootDomain} ${internalDomain} *.${internalDomain};
        return 301 https://$host$request_uri;
    }

    # --- ${internalDomain}: this host's own infrastructure tools ---------------

    # Portainer — docker management UI (tsvc-managed, published to loopback:9000
    # by SVC_PUBLISH_HOST in home/tsvc/services/portainer.env). Plain HTTP
    # inside its sidecar's netns; this proxy is what puts TLS in front of it.
    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name portainer.${internalDomain};

        ssl_certificate     /etc/nginx/certs/proxy.pem;
        ssl_certificate_key /etc/nginx/certs/proxy-key.pem;

        location / {
            proxy_pass http://127.0.0.1:9000;
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # Paisa — personal finance / ledger UI (tsvc-managed, published to
    # loopback:7500 by SVC_PUBLISH_HOST in home/tsvc/services/paisa.env).
    # 7500 is paisa's own port (SVC_PORT), not a proxy choice.
    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name paisa.${internalDomain};

        ssl_certificate     /etc/nginx/certs/proxy.pem;
        ssl_certificate_key /etc/nginx/certs/proxy-key.pem;

        location / {
            proxy_pass http://127.0.0.1:7500;
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # Anything else under ${internalDomain} is a typo, not a service: close the
    # connection rather than falling through to whichever block nginx picks
    # first (which would silently hand infra names to meddy's tier2).
    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name *.${internalDomain} ${internalDomain};

        ssl_certificate     /etc/nginx/certs/proxy.pem;
        ssl_certificate_key /etc/nginx/certs/proxy-key.pem;

        return 444;
    }

    # --- ${rootDomain}: meddy's dev stack -------------------------------------

    # Everything under ${rootDomain} -> meddy's own nginx (tier2), moved to
    # loopback:8080 by its local docker-compose.override.yml. meddy's nginx is
    # plain HTTP only — it never terminates TLS itself (same reasoning as this
    # proxy not trusting any project to manage its own cert: one edge
    # terminator, everything behind it plain HTTP, same as a real SaaS
    # deployment). meddy's own nginx.conf.template still owns the
    # web./app./api./swagger. split for that project — this proxy only routes to
    # it, never duplicates its logic.
    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name ${rootDomain} *.${rootDomain};

        ssl_certificate     /etc/nginx/certs/proxy.pem;
        ssl_certificate_key /etc/nginx/certs/proxy-key.pem;

        location / {
            proxy_pass http://127.0.0.1:8080;
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
  '';
in
lib.mkIf enable {
  home.file = {
    ".local/bin/system-proxy" = {
      source = ../.local/bin/system-proxy;
      executable = true;
    };
    ".config/system-proxy/conf.d/default.conf".source = defaultConf;

    # Read by the launcher, which issues one mkcert cert covering both
    # namespaces (`system-proxy certs`). Keep in sync with defaultConf above:
    # a domain served here but missing from config.env gets no SAN and fails
    # TLS; the reverse just means an unused SAN.
    ".config/system-proxy/config.env".text = ''
      # Managed by home/system-proxy.nix — do not edit.
      ROOT_DOMAIN=${rootDomain}
      INTERNAL_DOMAIN=${internalDomain}
    '';
  };
}
