# system-proxy — the box's single system-wide nginx reverse proxy (tier1).
#
# Everything else on this host binds only to loopback (meddy's own nginx,
# tsvc-managed services like Portainer); this is the ONLY thing bound to the
# real 0.0.0.0:80/443. It terminates TLS with one mkcert wildcard cert for
# ROOT_DOMAIN and fans out by Host header to each project's loopback port —
# each project keeps owning its own internal routing, so compose projects
# never need to share a docker network with each other or with this proxy.
# Runs with --network host (see the launcher) so its own 127.0.0.1 is the
# real host loopback — those loopback-published ports are NOT reachable via
# the docker0 bridge gateway (host.docker.internal), only genuine loopback.
# See .local/bin/system-proxy for the launcher itself.
#
# Installs the `system-proxy` launcher (.local/bin/system-proxy) plus its
# rendered nginx config. The TLS cert itself is NOT nix-managed (mkcert writes
# host-local state) — after `hm-switch`, run `system-proxy certs` once, then
# `system-proxy start`. Docker's `--restart=unless-stopped` means it survives
# reboots on its own from then on, same as tsvc/portainer (see home/tsvc.nix).
#
# Gated to Linux `server` hosts, same as tsvc/portainer. ROOT_DOMAIN is fixed
# per-host below — "meddy.test" is the only project deployed here today;
# extend defaultConf as more projects join.
{ lib, pkgs, role ? "client", ... }:
let
  enable = pkgs.stdenv.isLinux && role == "server";
  rootDomain = "meddy.test";

  defaultConf = pkgs.writeText "system-proxy-default.conf" ''
    # Generated by home/system-proxy.nix — do not edit, edit the .nix source.
    server {
        listen 80;
        listen [::]:80;
        server_name ${rootDomain} *.${rootDomain};
        return 301 https://$host$request_uri;
    }

    # Portainer (tsvc-managed, published to loopback:9000 — see
    # home/tsvc/services/portainer.env). An exact server_name match wins over
    # the catch-all wildcard below, so this block claims
    # portainer.${rootDomain} first.
    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name portainer.${rootDomain};

        ssl_certificate     /etc/nginx/certs/proxy.pem;
        ssl_certificate_key /etc/nginx/certs/proxy-key.pem;

        location / {
            proxy_pass http://127.0.0.1:9000;
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # Everything else -> meddy's own nginx, moved to loopback:8080 by its
    # local docker-compose.override.yml. meddy's nginx is plain HTTP only — it
    # never terminates TLS itself (same reasoning as this proxy not trusting
    # any project to manage its own cert: one edge terminator, everything
    # behind it plain HTTP, same as a real SaaS deployment). meddy's own
    # nginx.conf.template still owns the web./app./api. split for that
    # project — this proxy only routes to it, never duplicates its logic.
    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name ${rootDomain} *.${rootDomain};

        ssl_certificate     /etc/nginx/certs/proxy.pem;
        ssl_certificate_key /etc/nginx/certs/proxy-key.pem;

        location / {
            proxy_pass http://127.0.0.1:8080;
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
  '';
in
lib.mkIf enable {
  home.file = {
    ".local/bin/system-proxy" = {
      source = ../.local/bin/system-proxy;
      executable = true;
    };
    ".config/system-proxy/conf.d/default.conf".source = defaultConf;

    ".config/system-proxy/config.env".text = ''
      # Managed by home/system-proxy.nix — do not edit.
      ROOT_DOMAIN=${rootDomain}
    '';
  };
}
