# tsvc — Tailscale per-service subdomain routing on `server` hosts.
#
# Installs the `tsvc` helper (.local/bin/tsvc) plus the checked-in service
# definitions. Each service becomes its own tailnet device fronted by a
# `tailscale serve` sidecar, so it's reachable at
#   https://<svc>.<tailnet>.ts.net
# with a valid Tailscale cert and no external domain. See .local/bin/tsvc.
#
# Gated to Linux `server` hosts (same boxes that run dockerd + the portainer
# launcher). No-op everywhere else. The Tailscale OAuth secret that tsvc needs
# is declared in home/secrets.nix under the *same* gate; here we only surface
# its rendered path (authoritative from sops) to the script via config.env.
{ config, lib, pkgs, role ? "client", ... }:
let
  enable = pkgs.stdenv.isLinux && role == "server";
in
lib.mkIf enable {
  home.file = {
    ".local/bin/tsvc" = {
      source = ../.local/bin/tsvc;
      executable = true;
    };

    # Checked-in service definitions (ad-hoc ones can be added with `tsvc new`).
    ".config/tsvc/services/portainer.env".source = ./tsvc/services/portainer.env;
    ".config/tsvc/services/paisa.env".source = ./tsvc/services/paisa.env;
    ".config/tsvc/services/meddy.env".source = ./tsvc/services/meddy.env;

    # Runtime config for tsvc. Generated by nix so the sops render path stays
    # authoritative (tsvc reads the OAuth secret from this file, never hardcoded).
    ".config/tsvc/config.env".text = ''
      # Managed by home/tsvc.nix — do not edit.
      TS_AUTHKEY_FILE=${config.sops.secrets.tailscale_svc_oauth.path}
      TS_TAG=tag:svc
    '';
  };
}
